import Head from "next/head"

export default function Home() {
  return (
    <>
      <Head>
        <title>Link It</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className=" h-screen w-screen flex justify-center items-center bg-slate-200 ">
        <h1 className="text-2xl text-gray-800 ">Link It</h1>
      </div>
    </>
  )
}
